version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: filmslibrarydb
      MYSQL_ROOT_PASSWORD: 12345

  app:
    image: filmslibrary
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
#      MY_SQL_HOST: db
#      MY_SQL_PORT: 3307
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/filmslibrarydb?autoReconnect=true&useSSL=false
