version: '3.6'

services:
  db:
    image: mysql/mysql-server
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: filmslibrarydb
      MYSQL_ROOT_PASSWORD: 12345

  app:
    image: films_library
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: filmslibrarydb
      DB_USERNAME: mysql
      DB_PASSWORD: mysql
      JAR_NAME: FilmsLibrary-1
      WAIT_HOSTS: db:3306
